/// @version fmh [7c6f0fef29] 2010-10-06 15:54:29
/// @note generated by fmh -infile "C:\rev\src\ib\manifest" -prefix "IB_"

#pragma once

#ifndef IB_MANIFEST_DATE
#define IB_MANIFEST_DATE "2011-06-08 06:09:19.642"
#endif
