/// @version fmh [7c6f0fef29] 2010-10-06 15:54:29
/// @note generated by fmh -infile "C:\rev\src\ib\manifest.uuid" -prefix "IB_"

#pragma once

#ifndef IB_MANIFEST_UUID
#define IB_MANIFEST_UUID "a0140f0a31d7b7f97e6ca40aaaa15204054235cd"
#endif

#ifndef IB_MANIFEST_VERSION
#define IB_MANIFEST_VERSION "a0140f0a31"
#endif
